import { Interest, InterestCategory } from '../../interests/entities/interest.entity';

export interface InterestSeedData {
  name: string;
  description?: string;
  category: InterestCategory;
  icon?: string;
  color?: string;
  tags?: string[];
}

export const INTERESTS_SEED_DATA: InterestSeedData[] = [
  // SPORTS
  {
    name: 'Football',
    description: 'Le sport le plus populaire au monde',
    category: InterestCategory.SPORTS,
    icon: '⚽',
    color: '#1E88E5',
    tags: ['ballon', 'équipe', 'compétition'],
  },
  {
    name: 'Basketball',
    description: 'Sport d équipe très dynamique',
    category: InterestCategory.SPORTS,
    icon: '🏀',
    color: '#F57C00',
    tags: ['panier', 'NBA', 'équipe'],
  },
  {
    name: 'Tennis',
    description: 'Sport de raquette individuel ou en double',
    category: InterestCategory.SPORTS,
    icon: '🎾',
    color: '#43A047',
    tags: ['raquette', 'court', 'Roland-Garros'],
  },
  {
    name: 'Running',
    description: 'Course à pied pour le fitness ou la compétition',
    category: InterestCategory.SPORTS,
    icon: '🏃',
    color: '#E53935',
    tags: ['jogging', 'marathon', 'fitness'],
  },
  {
    name: 'Cycling',
    description: 'Vélo de route, VTT ou cyclisme urbain',
    category: InterestCategory.SPORTS,
    icon: '🚴',
    color: '#00897B',
    tags: ['vélo', 'VTT', 'route'],
  },
  {
    name: 'Swimming',
    description: 'Natation en piscine ou eau libre',
    category: InterestCategory.SPORTS,
    icon: '🏊',
    color: '#00ACC1',
    tags: ['nager', 'piscine', 'eau libre'],
  },
  {
    name: 'Yoga',
    description: 'Pratique du bien-être et de la méditation',
    category: InterestCategory.SPORTS,
    icon: '🧘',
    color: '#8E24AA',
    tags: ['méditation', 'flexibilité', 'zen'],
  },
  {
    name: 'Fitness',
    description: 'Musculation et entraînement en salle',
    category: InterestCategory.SPORTS,
    icon: '💪',
    color: '#D32F2F',
    tags: ['musculation', 'salle', 'force'],
  },
  {
    name: 'Hiking',
    description: 'Randonnée pédestre en montagne ou nature',
    category: InterestCategory.SPORTS,
    icon: '🥾',
    color: '#5D4037',
    tags: ['randonnée', 'montagne', 'nature'],
  },
  {
    name: 'Climbing',
    description: 'Escalade en salle ou en extérieur',
    category: InterestCategory.SPORTS,
    icon: '🧗',
    color: '#E64A19',
    tags: ['escalade', 'bloc', 'voie'],
  },
  {
    name: 'Skiing',
    description: 'Ski alpin ou nordique',
    category: InterestCategory.SPORTS,
    icon: '⛷️',
    color: '#FFFFFF',
    tags: ['neige', 'alpin', 'nordique'],
  },
  {
    name: 'Surfing',
    description: 'Surf et sports de glisse aquatiques',
    category: InterestCategory.SPORTS,
    icon: '🏄',
    color: '#0277BD',
    tags: ['océan', 'planche', 'vague'],
  },
  {
    name: 'Volleyball',
    description: 'Sport d équipe sur sable ou en salle',
    category: InterestCategory.SPORTS,
    icon: '🏐',
    color: '#FF6F00',
    tags: ['beach', 'équipe', 'filet'],
  },
  {
    name: 'Boxing',
    description: 'Boxe anglaise, française ou thaï',
    category: InterestCategory.SPORTS,
    icon: '🥊',
    color: '#C62828',
    tags: ['combat', 'ring', 'MMA'],
  },
  {
    name: 'Martial Arts',
    description: 'Arts martiaux : karaté, judo, taekwondo',
    category: InterestCategory.SPORTS,
    icon: '🥋',
    color: '#4E342E',
    tags: ['karaté', 'judo', 'taekwondo'],
  },
  {
    name: 'Golf',
    description: 'Golf sur parcours',
    category: InterestCategory.SPORTS,
    icon: '⛳',
    color: '#2E7D32',
    tags: ['parcours', 'club', 'trou'],
  },

  // MUSIC
  {
    name: 'Pop Music',
    description: 'Musique pop contemporaine',
    category: InterestCategory.MUSIC,
    icon: '🎵',
    color: '#E91E63',
    tags: ['contemporain', 'radio', 'hit'],
  },
  {
    name: 'Rock',
    description: 'Rock classique et moderne',
    category: InterestCategory.MUSIC,
    icon: '🎸',
    color: '#212121',
    tags: ['guitare', 'concert', 'album'],
  },
  {
    name: 'Jazz',
    description: 'Jazz classique et moderne',
    category: InterestCategory.MUSIC,
    icon: '🎷',
    color: '#3F51B5',
    tags: ['saxophone', 'improvisation', 'club'],
  },
  {
    name: 'Classical',
    description: 'Musique classique et orchestrale',
    category: InterestCategory.MUSIC,
    icon: '🎼',
    color: '#6A1B9A',
    tags: ['orchestre', 'opéra', 'symphonie'],
  },
  {
    name: 'Electronic',
    description: 'Musique électronique et EDM',
    category: InterestCategory.MUSIC,
    icon: '🎹',
    color: '#00BCD4',
    tags: ['DJ', 'festival', 'techno'],
  },
  {
    name: 'Hip Hop',
    description: 'Hip-hop et rap',
    category: InterestCategory.MUSIC,
    icon: '🎤',
    color: '#9C27B0',
    tags: ['rap', 'beat', 'freestyle'],
  },
  {
    name: 'Country',
    description: 'Musique country',
    category: InterestCategory.MUSIC,
    icon: '🤠',
    color: '#FFA726',
    tags: ['guitare', 'folk', 'Nashville'],
  },
  {
    name: 'Reggae',
    description: 'Reggae et musique jamaïcaine',
    category: InterestCategory.MUSIC,
    icon: '🎵',
    color: '#FFD54F',
    tags: ['Bob Marley', 'Caribbean', 'vibes'],
  },
  {
    name: 'R&B',
    description: 'Rhythm and Blues',
    category: InterestCategory.MUSIC,
    icon: '🎤',
    color: '#9C27B0',
    tags: ['soul', 'smooth', 'groove'],
  },
  {
    name: 'Metal',
    description: 'Heavy metal et dérivés',
    category: InterestCategory.MUSIC,
    icon: '🤘',
    color: '#424242',
    tags: ['guitare', 'concert', 'hardcore'],
  },
  {
    name: 'Folk',
    description: 'Musique folk traditionnelle',
    category: InterestCategory.MUSIC,
    icon: '🪕',
    color: '#8D6E63',
    tags: ['traditionnel', 'acoustique', 'stories'],
  },
  {
    name: 'Indie',
    description: 'Musique indépendante',
    category: InterestCategory.MUSIC,
    icon: '🎸',
    color: '#EC407A',
    tags: ['indépendant', 'alternative', 'underground'],
  },

  // ARTS
  {
    name: 'Painting',
    description: 'Peinture à l huile, aquarelle, acrylique',
    category: InterestCategory.ARTS,
    icon: '🎨',
    color: '#FF5722',
    tags: ['art', 'création', 'galerie'],
  },
  {
    name: 'Drawing',
    description: 'Dessin au crayon, fusain, encre',
    category: InterestCategory.ARTS,
    icon: '✏️',
    color: '#212121',
    tags: ['croquis', 'portrait', 'illustration'],
  },
  {
    name: 'Photography',
    description: 'Photographie numérique ou argentique',
    category: InterestCategory.ARTS,
    icon: '📷',
    color: '#263238',
    tags: ['photo', 'portrait', 'paysage'],
  },
  {
    name: 'Sculpture',
    description: 'Sculpture sur pierre, bois, métal',
    category: InterestCategory.ARTS,
    icon: '🗿',
    color: '#795548',
    tags: ['3D', 'art', 'création'],
  },
  {
    name: 'Writing',
    description: 'Écriture créative, poésie, romans',
    category: InterestCategory.ARTS,
    icon: '✍️',
    color: '#37474F',
    tags: ['poésie', 'roman', 'créatif'],
  },
  {
    name: 'Theater',
    description: 'Théâtre et arts de la scène',
    category: InterestCategory.ARTS,
    icon: '🎭',
    color: '#E91E63',
    tags: ['comédie', 'drame', 'scène'],
  },
  {
    name: 'Dance',
    description: 'Danse classique, moderne, hip-hop',
    category: InterestCategory.ARTS,
    icon: '💃',
    color: '#E91E63',
    tags: ['ballet', 'chorégraphie', 'mouvement'],
  },
  {
    name: 'Pottery',
    description: 'Poterie et céramique',
    category: InterestCategory.ARTS,
    icon: '🏺',
    color: '#8D6E63',
    tags: ['céramique', 'artisanat', 'terre'],
  },
  {
    name: 'Street Art',
    description: 'Street art et graffiti',
    category: InterestCategory.ARTS,
    icon: '🖌️',
    color: '#FF9800',
    tags: ['graffiti', 'mural', 'urbain'],
  },

  // TRAVEL
  {
    name: 'Backpacking',
    description: 'Voyage sac à dos',
    category: InterestCategory.TRAVEL,
    icon: '🎒',
    color: '#FF6F00',
    tags: ['aventure', 'budget', 'solo'],
  },
  {
    name: 'City Breaks',
    description: 'Séjours urbains et visites culturelles',
    category: InterestCategory.TRAVEL,
    icon: '🏙️',
    color: '#424242',
    tags: ['culture', 'monuments', 'museums'],
  },
  {
    name: 'Beach Holidays',
    description: 'Vacances au bord de mer',
    category: InterestCategory.TRAVEL,
    icon: '🏖️',
    color: '#00BCD4',
    tags: ['plage', 'détente', 'soleil'],
  },
  {
    name: 'Adventure Travel',
    description: 'Voyage aventure et expériences extrêmes',
    category: InterestCategory.TRAVEL,
    icon: '⛰️',
    color: '#4CAF50',
    tags: ['extrême', 'nature', 'adrénaline'],
  },
  {
    name: 'Cultural Tourism',
    description: 'Tourisme culturel et historique',
    category: InterestCategory.TRAVEL,
    icon: '🏛️',
    color: '#9E9E9E',
    tags: ['histoire', 'culture', 'patrimoine'],
  },
  {
    name: 'Road Trips',
    description: 'Voyage en voiture et road trips',
    category: InterestCategory.TRAVEL,
    icon: '🚗',
    color: '#FF5722',
    tags: ['route', 'liberté', 'exploration'],
  },
  {
    name: 'Wildlife',
    description: 'Observation de la faune et safaris',
    category: InterestCategory.TRAVEL,
    icon: '🦁',
    color: '#FF9800',
    tags: ['safari', 'nature', 'animaux'],
  },
  {
    name: 'Mountains',
    description: 'Randonnées et activités en montagne',
    category: InterestCategory.TRAVEL,
    icon: '⛰️',
    color: '#607D8B',
    tags: ['montagne', 'altitude', 'panorama'],
  },
  {
    name: 'Islands',
    description: 'Voyages sur des îles',
    category: InterestCategory.TRAVEL,
    icon: '🏝️',
    color: '#00BCD4',
    tags: ['île', 'tropical', 'paradis'],
  },

  // FOOD
  {
    name: 'Cooking',
    description: 'Cuisine et préparation de repas',
    category: InterestCategory.FOOD,
    icon: '👨‍🍳',
    color: '#FF5722',
    tags: ['recettes', 'gastronomie', 'chef'],
  },
  {
    name: 'Baking',
    description: 'Pâtisserie et boulangerie',
    category: InterestCategory.FOOD,
    icon: '🍰',
    color: '#FFB74D',
    tags: ['gâteau', 'pain', 'dessert'],
  },
  {
    name: 'Wine Tasting',
    description: 'Dégustation de vins',
    category: InterestCategory.FOOD,
    icon: '🍷',
    color: '#8E24AA',
    tags: ['vin', 'dégustation', 'sommelier'],
  },
  {
    name: 'Coffee',
    description: 'Culture du café et barista',
    category: InterestCategory.FOOD,
    icon: '☕',
    color: '#6D4C41',
    tags: ['café', 'barista', 'torréfaction'],
  },
  {
    name: 'Craft Beer',
    description: 'Bière artisanale',
    category: InterestCategory.FOOD,
    icon: '🍺',
    color: '#FF9800',
    tags: ['bière', 'artisanal', 'brasserie'],
  },
  {
    name: 'Italian Cuisine',
    description: 'Cuisine italienne',
    category: InterestCategory.FOOD,
    icon: '🍝',
    color: '#E53935',
    tags: ['pasta', 'pizza', 'Italie'],
  },
  {
    name: 'Asian Cuisine',
    description: 'Cuisine asiatique : japonaise, chinoise, thaï',
    category: InterestCategory.FOOD,
    icon: '🍜',
    color: '#F44336',
    tags: ['sushi', 'ramen', 'wok'],
  },
  {
    name: 'Vegan',
    description: 'Cuisine végétalienne',
    category: InterestCategory.FOOD,
    icon: '🥗',
    color: '#4CAF50',
    tags: ['végétalien', 'bio', 'healthy'],
  },
  {
    name: 'BBQ',
    description: 'Barbecue et grilling',
    category: InterestCategory.FOOD,
    icon: '🔥',
    color: '#F44336',
    tags: ['grill', 'extérieur', 'viande'],
  },
  {
    name: 'Street Food',
    description: 'Street food et cuisine de rue',
    category: InterestCategory.FOOD,
    icon: '🌮',
    color: '#FF9800',
    tags: ['street', 'rapide', 'culturel'],
  },

  // TECHNOLOGY
  {
    name: 'Programming',
    description: 'Développement logiciel et programmation',
    category: InterestCategory.TECHNOLOGY,
    icon: '💻',
    color: '#1976D2',
    tags: ['code', 'développement', 'software'],
  },
  {
    name: 'AI',
    description: 'Intelligence artificielle et machine learning',
    category: InterestCategory.TECHNOLOGY,
    icon: '🤖',
    color: '#00BCD4',
    tags: ['ML', 'deep learning', 'automation'],
  },
  {
    name: 'Gaming',
    description: 'Jeux vidéo et e-sports',
    category: InterestCategory.TECHNOLOGY,
    icon: '🎮',
    color: '#9C27B0',
    tags: ['console', 'PC', 'e-sport'],
  },
  {
    name: 'Web Development',
    description: 'Développement web frontend et backend',
    category: InterestCategory.TECHNOLOGY,
    icon: '🌐',
    color: '#2196F3',
    tags: ['web', 'frontend', 'backend'],
  },
  {
    name: 'Mobile Apps',
    description: 'Développement d applications mobiles',
    category: InterestCategory.TECHNOLOGY,
    icon: '📱',
    color: '#4CAF50',
    tags: ['iOS', 'Android', 'app'],
  },
  {
    name: 'Cryptocurrency',
    description: 'Crypto-monnaies et blockchain',
    category: InterestCategory.TECHNOLOGY,
    icon: '₿',
    color: '#FF9800',
    tags: ['bitcoin', 'blockchain', 'NFT'],
  },
  {
    name: '3D Printing',
    description: 'Impression 3D et fabrication',
    category: InterestCategory.TECHNOLOGY,
    icon: '🖨️',
    color: '#9E9E9E',
    tags: ['fabrication', 'prototype', 'design'],
  },
  {
    name: 'Cybersecurity',
    description: 'Sécurité informatique et hacking éthique',
    category: InterestCategory.TECHNOLOGY,
    icon: '🔐',
    color: '#F44336',
    tags: ['sécurité', 'hacking', 'pentest'],
  },
  {
    name: 'Data Science',
    description: 'Science des données et analytics',
    category: InterestCategory.TECHNOLOGY,
    icon: '📊',
    color: '#2196F3',
    tags: ['data', 'analytics', 'statistiques'],
  },
  {
    name: 'IoT',
    description: 'Internet des objets et domotique',
    category: InterestCategory.TECHNOLOGY,
    icon: '🏠',
    color: '#9E9E9E',
    tags: ['smart home', 'connected', 'automation'],
  },

  // HEALTH
  {
    name: 'Meditation',
    description: 'Méditation et pleine conscience',
    category: InterestCategory.HEALTH,
    icon: '🧘',
    color: '#8E24AA',
    tags: ['mindfulness', 'zen', 'bien-être'],
  },
  {
    name: 'Nutrition',
    description: 'Nutrition et alimentation saine',
    category: InterestCategory.HEALTH,
    icon: '🥗',
    color: '#4CAF50',
    tags: ['healthy', 'diet', 'bien-être'],
  },
  {
    name: 'Mental Health',
    description: 'Santé mentale et bien-être psychologique',
    category: InterestCategory.HEALTH,
    icon: '🧠',
    color: '#2196F3',
    tags: ['psychologie', 'bien-être', 'thérapie'],
  },
  {
    name: 'Wellness',
    description: 'Bien-être global et lifestyle',
    category: InterestCategory.HEALTH,
    icon: '✨',
    color: '#E91E63',
    tags: ['bien-être', 'lifestyle', 'balance'],
  },
  {
    name: 'Running',
    description: 'Course à pied pour la santé',
    category: InterestCategory.HEALTH,
    icon: '🏃',
    color: '#E53935',
    tags: ['cardio', 'fitness', 'santé'],
  },

  // EDUCATION
  {
    name: 'Languages',
    description: 'Apprentissage de langues étrangères',
    category: InterestCategory.EDUCATION,
    icon: '🗣️',
    color: '#2196F3',
    tags: ['bilingue', 'polyglotte', 'communication'],
  },
  {
    name: 'History',
    description: 'Histoire et cultures du monde',
    category: InterestCategory.EDUCATION,
    icon: '📜',
    color: '#795548',
    tags: ['culture', 'patrimoine', 'civilisation'],
  },
  {
    name: 'Philosophy',
    description: 'Philosophie et réflexion',
    category: InterestCategory.EDUCATION,
    icon: '🤔',
    color: '#546E7A',
    tags: ['réflexion', 'pensée', 'sagesse'],
  },
  {
    name: 'Science',
    description: 'Sciences naturelles et expérimentales',
    category: InterestCategory.EDUCATION,
    icon: '🔬',
    color: '#00BCD4',
    tags: ['expérimentation', 'découverte', 'recherche'],
  },
  {
    name: 'Online Courses',
    description: 'Formation en ligne et MOOCs',
    category: InterestCategory.EDUCATION,
    icon: '💻',
    color: '#2196F3',
    tags: ['apprentissage', 'formation', 'développement'],
  },
  {
    name: 'Reading',
    description: 'Lecture de livres et littérature',
    category: InterestCategory.EDUCATION,
    icon: '📚',
    color: '#5D4037',
    tags: ['livres', 'littérature', 'connaissance'],
  },

  // BUSINESS
  {
    name: 'Entrepreneurship',
    description: 'Entrepreneuriat et création d entreprise',
    category: InterestCategory.BUSINESS,
    icon: '💼',
    color: '#1976D2',
    tags: ['startup', 'business', 'innovation'],
  },
  {
    name: 'Investment',
    description: 'Investissement et finance',
    category: InterestCategory.BUSINESS,
    icon: '📈',
    color: '#4CAF50',
    tags: ['finance', 'bourse', 'économie'],
  },
  {
    name: 'Marketing',
    description: 'Marketing digital et communication',
    category: InterestCategory.BUSINESS,
    icon: '📢',
    color: '#FF9800',
    tags: ['communication', 'branding', 'digital'],
  },
  {
    name: 'Networking',
    description: 'Réseautage professionnel',
    category: InterestCategory.BUSINESS,
    icon: '🤝',
    color: '#2196F3',
    tags: ['contacts', 'professionnel', 'carrière'],
  },
  {
    name: 'Leadership',
    description: 'Leadership et management',
    category: InterestCategory.BUSINESS,
    icon: '👔',
    color: '#424242',
    tags: ['management', 'équipe', 'stratégie'],
  },

  // ENTERTAINMENT
  {
    name: 'Movies',
    description: 'Cinéma et films',
    category: InterestCategory.ENTERTAINMENT,
    icon: '🎬',
    color: '#E53935',
    tags: ['cinéma', 'films', 'festival'],
  },
  {
    name: 'TV Shows',
    description: 'Séries télévisées',
    category: InterestCategory.ENTERTAINMENT,
    icon: '📺',
    color: '#1976D2',
    tags: ['séries', 'streaming', 'binge'],
  },
  {
    name: 'Comics',
    description: 'BD, mangas et comics',
    category: InterestCategory.ENTERTAINMENT,
    icon: '📖',
    color: '#FF9800',
    tags: ['manga', 'comics', 'graphic novel'],
  },
  {
    name: 'Podcasts',
    description: 'Podcasts et audio content',
    category: InterestCategory.ENTERTAINMENT,
    icon: '🎧',
    color: '#9E9E9E',
    tags: ['audio', 'discussion', 'apprentissage'],
  },
  {
    name: 'Board Games',
    description: 'Jeux de société',
    category: InterestCategory.ENTERTAINMENT,
    icon: '🎲',
    color: '#8D6E63',
    tags: ['stratégie', 'social', 'famille'],
  },
  {
    name: 'Magic',
    description: 'Magie et tours de magie',
    category: InterestCategory.ENTERTAINMENT,
    icon: '🪄',
    color: '#9C27B0',
    tags: ['illusion', 'spectacle', 'mystère'],
  },

  // LIFESTYLE
  {
    name: 'Fashion',
    description: 'Mode et style vestimentaire',
    category: InterestCategory.LIFESTYLE,
    icon: '👗',
    color: '#E91E63',
    tags: ['style', 'vêtements', 'trends'],
  },
  {
    name: 'Interior Design',
    description: 'Décoration intérieure et design',
    category: InterestCategory.LIFESTYLE,
    icon: '🏠',
    color: '#FF9800',
    tags: ['décoration', 'architecture', 'aménagement'],
  },
  {
    name: 'Gardening',
    description: 'Jardinage et plantes',
    category: InterestCategory.LIFESTYLE,
    icon: '🌱',
    color: '#4CAF50',
    tags: ['plantes', 'nature', 'verdure'],
  },
  {
    name: 'Pets',
    description: 'Animaux de compagnie',
    category: InterestCategory.LIFESTYLE,
    icon: '🐕',
    color: '#FF9800',
    tags: ['chien', 'chat', 'animal'],
  },
  {
    name: 'Minimalism',
    description: 'Minimalisme et simplicité volontaire',
    category: InterestCategory.LIFESTYLE,
    icon: '✨',
    color: '#9E9E9E',
    tags: ['simplicité', 'épuration', 'essentiel'],
  },
  {
    name: 'Sustainable Living',
    description: 'Vie durable et écologique',
    category: InterestCategory.LIFESTYLE,
    icon: '🌍',
    color: '#4CAF50',
    tags: ['écologie', 'durable', 'green'],
  },

  // OTHER
  {
    name: 'Astrology',
    description: 'Astrologie et horoscopes',
    category: InterestCategory.OTHER,
    icon: '⭐',
    color: '#9C27B0',
    tags: ['zodiaque', 'planètes', 'mystique'],
  },
  {
    name: 'Collecting',
    description: 'Collection d objets',
    category: InterestCategory.OTHER,
    icon: '🔍',
    color: '#607D8B',
    tags: ['collection', 'antiquités', 'vintage'],
  },
  {
    name: 'Volunteering',
    description: 'Bénévolat et actions solidaires',
    category: InterestCategory.OTHER,
    icon: '🤲',
    color: '#4CAF50',
    tags: ['solidarité', 'humanitaire', 'engagement'],
  },
  {
    name: 'Outdoor',
    description: 'Activités en plein air',
    category: InterestCategory.OTHER,
    icon: '🌲',
    color: '#4CAF50',
    tags: ['nature', 'extérieur', 'air libre'],
  },
];



